"""
Mock Executor — runs the full CognivCrew pipeline with zero LLM calls.

Enabled via EXECUTION_MODE=mock in .env.
Useful for testing pipeline structure, output file layout, and CLI UX without
consuming API tokens or requiring any external service.

The engineer stage always produces a hello_world.py application.
"""
import time
from pathlib import Path

from loguru import logger
from rich.console import Console
from rich.panel import Panel

from config import cfg
from graph.state import CognivCrewState

console = Console()

# ---------------------------------------------------------------------------
# Pre-canned stage content
# ---------------------------------------------------------------------------

_MOCK_STRATEGY = """
# CEO Strategy — Mock

**Vision:** Deliver the simplest possible working application that validates
the end-to-end CognivCrew pipeline without any LLM calls.

**Goal:** Produce a Hello World program as the canonical smoke-test artefact.

**Constraints:**
- Zero external dependencies
- Single source file
- Runs with a standard Python interpreter
""".strip()

_MOCK_PRODUCT_SPEC = """
# Product Specification — Mock

## User Request
{user_request}

## Epics
1. **Hello World** — Display a greeting message on execution.

## User Stories
- As a developer, I want to run a single command and see output so that I can
  confirm the pipeline produced a working program.

## Acceptance Criteria
1. Running `python hello_world.py` prints exactly `Hello, World!` to stdout.
2. The program exits with code 0.
3. No external packages are required.

## Technical Constraints
- Language: Python 3.x
- Single-file deliverable: `hello_world.py`
- No dependencies beyond the standard library
""".strip()

_MOCK_ARCHITECT_BRIEF = """
# Architecture Brief — Mock

## Chosen Pattern
Single-file CLI script — no framework, no build step.

## Rationale
The product requirement is a single console greeting. Any additional structure
(packages, modules, entry-point wrappers) would be disproportionate overhead.

## Components
| Component | Description |
|-----------|-------------|
| `hello_world.py` | Sole deliverable — one `print` statement. |

## Tech Stack
- **Language:** Python 3.x (stdlib only)
- **Runtime:** Any CPython 3.8+ interpreter
- **Packaging:** None — run directly with `python hello_world.py`

## ADR-01 — No Framework
Using a raw `print()` call satisfies all requirements. Importing any framework
would add installation complexity with zero functional benefit.
""".strip()

_MOCK_DESIGN_BRIEF = """
# Design Brief — Mock

## User Journey
1. Developer opens a terminal.
2. Developer runs: `python hello_world.py`
3. Terminal displays: `Hello, World!`
4. Program exits cleanly.

## Interaction Pattern
- **Input:** None (no arguments, no stdin)
- **Output:** Single line to stdout
- **Error states:** None anticipated

## Accessibility
Plain text output — compatible with all terminal emulators and screen readers.
""".strip()

_MOCK_IMPLEMENTATION_PLAN = """
# Implementation Plan — Mock

## Deliverable
`hello_world.py` — a minimal Python application.

## Source Code

```python
# hello_world.py
def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
```

## How to Run
```bash
python hello_world.py
# Output: Hello, World!
```

## Test
```bash
python -c "
import subprocess, sys
r = subprocess.run([sys.executable, 'hello_world.py'], capture_output=True, text=True)
assert r.returncode == 0
assert r.stdout.strip() == 'Hello, World!'
print('test passed')
"
```
""".strip()

_HELLO_WORLD_SOURCE = '''\
# hello_world.py — generated by CognivCrew (mock mode)


def main():
    print("Hello, World!")


if __name__ == "__main__":
    main()
'''

_MOCK_QA_REPORT = """
# QA Report — Mock

## Traceability Matrix

| Acceptance Criterion | Status |
|----------------------|--------|
| `python hello_world.py` prints `Hello, World!` | ✓ PASS |
| Exit code 0 | ✓ PASS |
| No external dependencies | ✓ PASS |

## Issue Log
No issues found.

## Final Verdict
VERDICT: PASS
""".strip()


# ---------------------------------------------------------------------------
# MockExecutor
# ---------------------------------------------------------------------------

class MockExecutor:
    """
    Executes every pipeline stage without any LLM call.

    Each stage writes its output file(s) and updates the state dict exactly as
    the real agents do, so downstream stages and the final node receive a
    fully-populated state.
    """

    def __init__(self) -> None:
        self._timings: dict[str, float] = {}

    @property
    def agent_timings(self) -> dict[str, float]:
        return dict(self._timings)

    def cost_report(self) -> str:
        return "Cost: $0.00 (mock mode — no LLM calls)"

    def run_all(
        self,
        state: CognivCrewState,
        approval_callback,
        max_architect_iterations: int,
    ) -> CognivCrewState:
        """Run all stages sequentially, honouring the architect approval gate."""
        state = self._run_ceo(state)
        state = self._run_pm(state)

        # Architect loop — mirrors the real pipeline approval gate
        while True:
            state = self._run_architect(state)
            arch_iter = state.get("architect_iteration", 0)

            if arch_iter >= max_architect_iterations:
                logger.warning(
                    f"Max architect iterations ({max_architect_iterations}) reached — force-approving"
                )
                state["architect_approved"] = True
                state["human_feedback"] = ""
            else:
                updates = approval_callback(state)
                state.update(updates)

            if state.get("architect_approved"):
                break

        state = self._run_designer(state)
        state = self._run_engineer(state)
        state = self._run_qa(state)
        return state

    # ── Stage implementations ─────────────────────────────────────────────

    def _run_ceo(self, state: CognivCrewState) -> CognivCrewState:
        t0 = time.perf_counter()
        logger.info("Mock CEO agent starting")
        state["strategy"] = _MOCK_STRATEGY
        self._timings["ceo"] = time.perf_counter() - t0
        logger.info("Mock CEO agent complete")
        console.print(Panel(
            "[bold green]CEO strategy complete.[/bold green] [dim](mock)[/dim]",
            title="[bold cyan]CEO Agent[/bold cyan]",
            expand=False,
        ))
        return state

    def _run_pm(self, state: CognivCrewState) -> CognivCrewState:
        t0 = time.perf_counter()
        logger.info("Mock PM agent starting")
        content = _MOCK_PRODUCT_SPEC.format(user_request=state.get("user_request", ""))
        state["product_spec"] = content
        output_path = Path(state["output_dir"]) / cfg.FILE_PRODUCT_SPEC
        output_path.write_text(content)
        self._timings["pm"] = time.perf_counter() - t0
        logger.info(f"Mock PM agent complete — {output_path}")
        console.print(Panel(
            f"[bold green]Product specification complete.[/bold green] [dim](mock)[/dim]\n"
            f"Saved to: [bold white]{output_path}[/bold white]",
            title="[bold cyan]PM Agent[/bold cyan]",
            expand=False,
        ))
        return state

    def _run_architect(self, state: CognivCrewState) -> CognivCrewState:
        t0 = time.perf_counter()
        arch_iter = state.get("architect_iteration", 0)
        logger.info(f"Mock Architect agent starting (iteration {arch_iter})")
        state["architect_brief"] = _MOCK_ARCHITECT_BRIEF
        state["architect_iteration"] = arch_iter + 1
        output_path = Path(state["output_dir"]) / cfg.FILE_ARCHITECT_BRIEF
        output_path.write_text(_MOCK_ARCHITECT_BRIEF)
        self._timings["architect"] = time.perf_counter() - t0
        logger.info(f"Mock Architect agent complete — {output_path}")
        console.print(Panel(
            f"[bold green]Architecture brief complete.[/bold green] "
            f"Iteration: [bold white]{state['architect_iteration']}[/bold white] [dim](mock)[/dim]\n"
            f"Saved to: [bold white]{output_path}[/bold white]",
            title="[bold cyan]Architect Agent[/bold cyan]",
            expand=False,
        ))
        return state

    def _run_designer(self, state: CognivCrewState) -> CognivCrewState:
        t0 = time.perf_counter()
        logger.info("Mock Designer agent starting")
        state["design_brief"] = _MOCK_DESIGN_BRIEF
        output_path = Path(state["output_dir"]) / cfg.FILE_DESIGN_BRIEF
        output_path.write_text(_MOCK_DESIGN_BRIEF)
        self._timings["designer"] = time.perf_counter() - t0
        logger.info(f"Mock Designer agent complete — {output_path}")
        console.print(Panel(
            f"[bold green]Design brief complete.[/bold green] [dim](mock)[/dim]\n"
            f"Saved to: [bold white]{output_path}[/bold white]",
            title="[bold cyan]Designer Agent[/bold cyan]",
            expand=False,
        ))
        return state

    def _run_engineer(self, state: CognivCrewState) -> CognivCrewState:
        t0 = time.perf_counter()
        iteration = state.get("iteration", 0)
        logger.info(f"Mock Engineer agent starting (iteration {iteration})")
        state["implementation_plan"] = _MOCK_IMPLEMENTATION_PLAN
        output_dir = Path(state["output_dir"])
        plan_path = output_dir / cfg.FILE_IMPLEMENTATION_PLAN
        plan_path.write_text(_MOCK_IMPLEMENTATION_PLAN)
        hw_path = output_dir / "hello_world.py"
        hw_path.write_text(_HELLO_WORLD_SOURCE)
        self._timings["engineer"] = time.perf_counter() - t0
        logger.info(f"Mock Engineer agent complete — {plan_path}, {hw_path}")
        console.print(Panel(
            f"[bold green]Implementation plan complete.[/bold green] [dim](mock)[/dim]\n"
            f"Plan:      [bold white]{plan_path}[/bold white]\n"
            f"Hello World: [bold white]{hw_path}[/bold white]",
            title="[bold cyan]Engineer Agent[/bold cyan]",
            expand=False,
        ))
        return state

    def _run_qa(self, state: CognivCrewState) -> CognivCrewState:
        t0 = time.perf_counter()
        iteration = state.get("iteration", 0) + 1
        logger.info(f"Mock QA agent starting (iteration {iteration})")
        state["qa_verdict"] = _MOCK_QA_REPORT
        state["qa_feedback"] = ""
        state["iteration"] = iteration
        output_path = Path(state["output_dir"]) / cfg.FILE_QA_REPORT
        output_path.write_text(_MOCK_QA_REPORT)
        self._timings["qa"] = time.perf_counter() - t0
        logger.info(f"Mock QA agent complete — VERDICT: PASS — {output_path}")
        console.print(Panel(
            f"Verdict: [bold green]PASS[/bold green]   |   "
            f"Iteration: [bold white]{iteration}[/bold white] [dim](mock)[/dim]\n"
            f"Saved to: [bold white]{output_path}[/bold white]",
            title="[bold cyan]QA Agent[/bold cyan]",
            expand=False,
        ))
        return state
